.myfunc.env = new.env()
sys.source("needleman_wunsch/functions.R", envir = .myfunc.env)
sys.source("needleman_wunsch/needlemanWunsch.R", envir = .myfunc.env)
sys.source("needleman_wunsch/makeScoringMatrix.R", envir = .myfunc.env)
attach(.myfunc.env)

seq1 <- c("n", "a") 
seq2 <- c("n", "a:")
scoring_matrix <- makeScoringMatrix()
needlemanWunsch(seq1, seq2, s = scoring_matrix)
